services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: media
      POSTGRES_PASSWORD: welcome
      POSTGRES_DB: media
    volumes:
      - ./resources/database/migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
