[package]
name = "foundation"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
aws-sdk-s3.workspace = true
aws-sdk-sqs.workspace = true
aws-config.workspace = true
cloudfront_sign.workspace = true
async-trait.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
chrono.workspace = true
ulid.workspace = true
regex.workspace = true

[dev-dependencies]
rstest.workspace = true
tokio = { workspace = true, features = ["full"] }
