[package]
name = "foundation"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
async-trait.workspace = true
chrono.workspace = true

aws-config = "1"
aws-sdk-s3 = "1"
aws-sdk-sqs = "1"
cloudfront_sign = "0.4"
regex = "1"
sqlx = { version = "0.8", features = [
    "runtime-tokio-rustls",
    "postgres",
    "chrono",
] }
thiserror.workspace = true
ulid = { version = "1", features = ["serde"] }

[dev-dependencies]
rstest.workspace = true
